version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    working_dir: /usr/src/db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - $DB_PORT:5432
