import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex.raw(`
  DELETE FROM "Todos";
  DELETE FROM "Users";

  ALTER SEQUENCE "Todos_id_seq" RESTART WITH 1;
  ALTER SEQUENCE "Users_id_seq" RESTART WITH 1;

  insert into "Users" (id, name) values (1, 'Layney');
  insert into "Users" (id, name) values (2, 'Alexandrina');
  insert into "Users" (id, name) values (3, 'Eloise');
  insert into "Users" (id, name) values (4, 'Dahlia');
  insert into "Users" (id, name) values (5, 'Nomi');
  insert into "Users" (id, name) values (6, 'Loria');
  insert into "Users" (id, name) values (7, 'Constantina');
  insert into "Users" (id, name) values (8, 'Cordie');
  insert into "Users" (id, name) values (9, 'Costanza');
  insert into "Users" (id, name) values (10, 'Dulce');
  insert into "Users" (id, name) values (11, 'Lu');
  insert into "Users" (id, name) values (12, 'Gretta');
  insert into "Users" (id, name) values (13, 'Binnie');
  insert into "Users" (id, name) values (14, 'Stacee');
  insert into "Users" (id, name) values (15, 'Carie');
  insert into "Users" (id, name) values (16, 'Nellie');
  insert into "Users" (id, name) values (17, 'Margaretta');
  insert into "Users" (id, name) values (18, 'Mildrid');
  insert into "Users" (id, name) values (19, 'Lauralee');
  insert into "Users" (id, name) values (20, 'Bunni');
  insert into "Users" (id, name) values (21, 'Melva');
  insert into "Users" (id, name) values (22, 'Michelina');
  insert into "Users" (id, name) values (23, 'Stephani');
  insert into "Users" (id, name) values (24, 'Gabriellia');
  insert into "Users" (id, name) values (25, 'Lura');
  insert into "Users" (id, name) values (26, 'Edie');
  insert into "Users" (id, name) values (27, 'Katharyn');
  insert into "Users" (id, name) values (28, 'Meggi');
  insert into "Users" (id, name) values (29, 'Junie');
  insert into "Users" (id, name) values (30, 'Batsheva');
  insert into "Users" (id, name) values (31, 'Dina');
  insert into "Users" (id, name) values (32, 'Catriona');
  insert into "Users" (id, name) values (33, 'Holly');
  insert into "Users" (id, name) values (34, 'Deeanne');
  insert into "Users" (id, name) values (35, 'Addia');
  insert into "Users" (id, name) values (36, 'Stephana');
  insert into "Users" (id, name) values (37, 'Sidonia');
  insert into "Users" (id, name) values (38, 'Gerrie');
  insert into "Users" (id, name) values (39, 'Tammie');
  insert into "Users" (id, name) values (40, 'Loella');
  insert into "Users" (id, name) values (41, 'Gertruda');
  insert into "Users" (id, name) values (42, 'Bridie');
  insert into "Users" (id, name) values (43, 'Charita');
  insert into "Users" (id, name) values (44, 'Maridel');
  insert into "Users" (id, name) values (45, 'Mona');
  insert into "Users" (id, name) values (46, 'Luci');
  insert into "Users" (id, name) values (47, 'Kimberlyn');
  insert into "Users" (id, name) values (48, 'Jessi');
  insert into "Users" (id, name) values (49, 'Gloria');
  insert into "Users" (id, name) values (50, 'Xenia');
  insert into "Users" (id, name) values (51, 'Anneliese');
  insert into "Users" (id, name) values (52, 'Gleda');
  insert into "Users" (id, name) values (53, 'Tarra');
  insert into "Users" (id, name) values (54, 'Fredericka');
  insert into "Users" (id, name) values (55, 'Cherida');
  insert into "Users" (id, name) values (56, 'Mariquilla');
  insert into "Users" (id, name) values (57, 'Janifer');
  insert into "Users" (id, name) values (58, 'Jeanne');
  insert into "Users" (id, name) values (59, 'Heloise');
  insert into "Users" (id, name) values (60, 'Candy');
  insert into "Users" (id, name) values (61, 'Natassia');
  insert into "Users" (id, name) values (62, 'Georgine');
  insert into "Users" (id, name) values (63, 'Jyoti');
  insert into "Users" (id, name) values (64, 'Elane');
  insert into "Users" (id, name) values (65, 'Karolina');
  insert into "Users" (id, name) values (66, 'Marice');
  insert into "Users" (id, name) values (67, 'Mareah');
  insert into "Users" (id, name) values (68, 'Melissa');
  insert into "Users" (id, name) values (69, 'Keeley');
  insert into "Users" (id, name) values (70, 'Quintina');
  insert into "Users" (id, name) values (71, 'Sher');
  insert into "Users" (id, name) values (72, 'Adan');
  insert into "Users" (id, name) values (73, 'Vivi');
  insert into "Users" (id, name) values (74, 'Barbette');
  insert into "Users" (id, name) values (75, 'Halette');
  insert into "Users" (id, name) values (76, 'Tracy');
  insert into "Users" (id, name) values (77, 'Tarra');
  insert into "Users" (id, name) values (78, 'Cherise');
  insert into "Users" (id, name) values (79, 'Clarissa');
  insert into "Users" (id, name) values (80, 'Roanne');
  insert into "Users" (id, name) values (81, 'Constantine');
  insert into "Users" (id, name) values (82, 'Cathleen');
  insert into "Users" (id, name) values (83, 'Iris');
  insert into "Users" (id, name) values (84, 'Bria');
  insert into "Users" (id, name) values (85, 'Kandace');
  insert into "Users" (id, name) values (86, 'Jessy');
  insert into "Users" (id, name) values (87, 'Scarlett');
  insert into "Users" (id, name) values (88, 'Sonja');
  insert into "Users" (id, name) values (89, 'Bendite');
  insert into "Users" (id, name) values (90, 'Sosanna');
  insert into "Users" (id, name) values (91, 'Alexi');
  insert into "Users" (id, name) values (92, 'Stephie');
  insert into "Users" (id, name) values (93, 'Tessy');
  insert into "Users" (id, name) values (94, 'Anette');
  insert into "Users" (id, name) values (95, 'Shaina');
  insert into "Users" (id, name) values (96, 'Bathsheba');
  insert into "Users" (id, name) values (97, 'Latashia');
  insert into "Users" (id, name) values (98, 'Mab');
  insert into "Users" (id, name) values (99, 'Anjela');
  insert into "Users" (id, name) values (100, 'Meade');

  insert into "Todos" (userId, title, completed) values (79, 'Bison, american', true);
  insert into "Todos" (userId, title, completed) values (4, 'Jungle cat', false);
  insert into "Todos" (userId, title, completed) values (46, 'Polecat, african', false);
  insert into "Todos" (userId, title, completed) values (89, 'Red-shouldered glossy starling', false);
  insert into "Todos" (userId, title, completed) values (46, 'Screamer, southern', true);
  insert into "Todos" (userId, title, completed) values (66, 'Gonolek, burchell''s', true);
  insert into "Todos" (userId, title, completed) values (79, 'Wild water buffalo', false);
  insert into "Todos" (userId, title, completed) values (48, 'Rabbit, eastern cottontail', false);
  insert into "Todos" (userId, title, completed) values (13, 'Yellow-bellied marmot', false);
  insert into "Todos" (userId, title, completed) values (35, 'Blue-tongued skink', false);
  insert into "Todos" (userId, title, completed) values (75, 'Stork, white', false);
  insert into "Todos" (userId, title, completed) values (37, 'Wallaroo, common', false);
  insert into "Todos" (userId, title, completed) values (35, 'Meerkat', false);
  insert into "Todos" (userId, title, completed) values (53, 'Secretary bird', false);
  insert into "Todos" (userId, title, completed) values (35, 'Nutcracker, clark''s', false);
  insert into "Todos" (userId, title, completed) values (91, 'Fringe-eared oryx', false);
  insert into "Todos" (userId, title, completed) values (59, 'Grey mouse lemur', true);
  insert into "Todos" (userId, title, completed) values (68, 'Stork, yellow-billed', true);
  insert into "Todos" (userId, title, completed) values (77, 'American woodcock', true);
  insert into "Todos" (userId, title, completed) values (76, 'Snow goose', false);
  insert into "Todos" (userId, title, completed) values (36, 'Eagle, bateleur', false);
  insert into "Todos" (userId, title, completed) values (72, 'Silver gull', true);
  insert into "Todos" (userId, title, completed) values (72, 'Gray heron', false);
  insert into "Todos" (userId, title, completed) values (56, 'Brazilian tapir', true);
  insert into "Todos" (userId, title, completed) values (98, 'African polecat', true);
  insert into "Todos" (userId, title, completed) values (71, 'Rat, arboral spiny', false);
  insert into "Todos" (userId, title, completed) values (25, 'Ringtail, common', true);
  insert into "Todos" (userId, title, completed) values (47, 'Pale white-eye', true);
  insert into "Todos" (userId, title, completed) values (89, 'Goose, andean', true);
  insert into "Todos" (userId, title, completed) values (40, 'Sun gazer', false);
  insert into "Todos" (userId, title, completed) values (81, 'Red brocket', true);
  insert into "Todos" (userId, title, completed) values (3, 'Wallaby, river', true);
  insert into "Todos" (userId, title, completed) values (72, 'Legaan, ground', false);
  insert into "Todos" (userId, title, completed) values (84, 'Seal, harbor', true);
  insert into "Todos" (userId, title, completed) values (42, 'Snowy sheathbill', false);
  insert into "Todos" (userId, title, completed) values (72, 'Capuchin, white-fronted', false);
  insert into "Todos" (userId, title, completed) values (14, 'Otter, cape clawless', false);
  insert into "Todos" (userId, title, completed) values (36, 'Margay', true);
  insert into "Todos" (userId, title, completed) values (87, 'Monkey, black spider', false);
  insert into "Todos" (userId, title, completed) values (40, 'Paradoxure', true);
  insert into "Todos" (userId, title, completed) values (19, 'European shelduck', false);
  insert into "Todos" (userId, title, completed) values (69, 'Red-headed woodpecker', true);
  insert into "Todos" (userId, title, completed) values (89, 'Long-crested hawk eagle', true);
  insert into "Todos" (userId, title, completed) values (61, 'African buffalo', true);
  insert into "Todos" (userId, title, completed) values (59, 'Galapagos mockingbird', true);
  insert into "Todos" (userId, title, completed) values (10, 'White-eye, pale', true);
  insert into "Todos" (userId, title, completed) values (59, 'Fox, silver-backed', false);
  insert into "Todos" (userId, title, completed) values (50, 'Otter, african clawless', false);
  insert into "Todos" (userId, title, completed) values (90, 'Pied avocet', false);
  insert into "Todos" (userId, title, completed) values (86, 'Eagle, long-crested hawk', false);
  insert into "Todos" (userId, title, completed) values (31, 'Tortoise, indian star', true);
  insert into "Todos" (userId, title, completed) values (30, 'White-fronted capuchin', true);
  insert into "Todos" (userId, title, completed) values (23, 'White stork', false);
  insert into "Todos" (userId, title, completed) values (61, 'Brown capuchin', false);
  insert into "Todos" (userId, title, completed) values (94, 'Corella, long-billed', false);
  insert into "Todos" (userId, title, completed) values (66, 'Gecko, tokay', false);
  insert into "Todos" (userId, title, completed) values (65, 'Lapwing, southern', true);
  insert into "Todos" (userId, title, completed) values (33, 'Owl, australian masked', false);
  insert into "Todos" (userId, title, completed) values (100, 'White-throated robin', true);
  insert into "Todos" (userId, title, completed) values (4, 'Great horned owl', true);
  insert into "Todos" (userId, title, completed) values (8, 'Bear, american black', false);
  insert into "Todos" (userId, title, completed) values (91, 'Duiker, common', false);
  insert into "Todos" (userId, title, completed) values (27, 'Ornate rock dragon', true);
  insert into "Todos" (userId, title, completed) values (70, 'Bird (unidentified)', false);
  insert into "Todos" (userId, title, completed) values (3, 'Nuthatch, red-breasted', true);
  insert into "Todos" (userId, title, completed) values (22, 'Cat, long-tailed spotted', false);
  insert into "Todos" (userId, title, completed) values (5, 'Hawk, red-tailed', false);
  insert into "Todos" (userId, title, completed) values (32, 'Common raccoon', false);
  insert into "Todos" (userId, title, completed) values (78, 'Orca', false);
  insert into "Todos" (userId, title, completed) values (18, 'Snowy sheathbill', false);
  insert into "Todos" (userId, title, completed) values (6, 'Cockatoo, slender-billed', true);
  insert into "Todos" (userId, title, completed) values (7, 'Common palm civet', true);
  insert into "Todos" (userId, title, completed) values (70, 'Waterbuck, common', false);
  insert into "Todos" (userId, title, completed) values (46, 'Snake, green vine', true);
  insert into "Todos" (userId, title, completed) values (56, 'Openbill, asian', false);
  insert into "Todos" (userId, title, completed) values (11, 'Roseate cockatoo', false);
  insert into "Todos" (userId, title, completed) values (62, 'Possum, ring-tailed', true);
  insert into "Todos" (userId, title, completed) values (70, 'Sparrow, house', true);
  insert into "Todos" (userId, title, completed) values (91, 'Common palm civet', true);
  insert into "Todos" (userId, title, completed) values (12, 'Bandicoot, southern brown', false);
  insert into "Todos" (userId, title, completed) values (17, 'Stork, black-necked', false);
  insert into "Todos" (userId, title, completed) values (76, 'Cape white-eye', false);
  insert into "Todos" (userId, title, completed) values (23, 'Red howler monkey', true);
  insert into "Todos" (userId, title, completed) values (21, 'Gull, silver', false);
  insert into "Todos" (userId, title, completed) values (72, 'Mexican wolf', true);
  insert into "Todos" (userId, title, completed) values (98, 'Crested barbet', true);
  insert into "Todos" (userId, title, completed) values (62, 'Spurfowl, yellow-necked', true);
  insert into "Todos" (userId, title, completed) values (18, 'Civet, small-toothed palm', false);
  insert into "Todos" (userId, title, completed) values (87, 'Gerbil (unidentified)', false);
  insert into "Todos" (userId, title, completed) values (86, 'Bat, madagascar fruit', false);
  insert into "Todos" (userId, title, completed) values (70, 'Cat, kaffir', true);
  insert into "Todos" (userId, title, completed) values (21, 'Dolphin, common', false);
  insert into "Todos" (userId, title, completed) values (26, 'Red-capped cardinal', true);
  insert into "Todos" (userId, title, completed) values (17, 'Bee-eater (unidentified)', false);
  insert into "Todos" (userId, title, completed) values (62, 'Black and white colobus', false);
  insert into "Todos" (userId, title, completed) values (97, 'Blue-breasted cordon bleu', true);
  insert into "Todos" (userId, title, completed) values (99, 'Turkey, australian brush', true);
  insert into "Todos" (userId, title, completed) values (68, 'Hyrax', false);
  insert into "Todos" (userId, title, completed) values (45, 'Fox, pampa gray', false);
  insert into "Todos" (userId, title, completed) values (20, 'Laughing dove', true);
  `);
}
